apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testweb-nginx2
  name: test-web-nginx2
  namespace: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testweb-nginx2
  template:
    metadata:
      labels:
        app: testweb-nginx2
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
