apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testweb-nginx1
  name: test-web-nginx1
  namespace: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testweb-nginx1
  template:
    metadata:
      labels:
       app: testweb-nginx1
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
       - name: html-volume
         configMap:
           name: pocetna-strana
