apiVersion: v1
kind: Service
metadata:
  name: testweb-nginx1
  namespace: web-app
spec:
  selector:
    app: testweb-nginx1
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
